# Generated by Django 5.1.3 on 2024-12-25 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminside', '0001_initial'),
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='contact_form.newlabel'),
        ),
        migrations.AddField(
            model_name='weight',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='contact_form.newlabel'),
        ),
    ]
