# Generated by Django 5.1.3 on 2024-12-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='value',
            field=models.CharField(choices=[('Priority', 'Priority'), ('Express', 'Express'), ('First Class', 'First Class'), ('Signature', 'Signature')], default='Priority', max_length=100),
        ),
    ]
